// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:643581a7-d8c7-474a-abf6-f305292ec299',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'newapp-hosting-mobilehub-1711215112',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1mp6xyoz3vxwb.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f6ae155f31d94e0aa508569d1fba469a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '43612048-1522-11e8-b5df-89121fa705ee',
    'aws_project_name': 'newApp',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'newapp-mobilehub-1711215112',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'newapp-userfiles-mobilehub-1711215112',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_Fe0ROUqHx',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1c1hmms7j1odlqll8d5j5dafc6',
}

export default awsmobile;
